from enum import Enum

class DatasetName(Enum):
    AITDNA = "AITDNA"
    AITDNA_SYNTHETIC = "AITDNA_SYNTHETIC"
    COAUTHOR = "COAUTHOR"
    MIXSET = "MIXSET"
    DETECTRL = "DETECTRL"
    BOUNDARY_DETECTION = "BOUNDARY_DETECTION"
    SENDETEX= "SENDETEX"